#!/usr/bin/env bash
#that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
