#!/usr/bin/env bash
# 1. What type of network a computer in local is connected to
# 2. What type of network could connect an office in one building to
# another office in a building a few streets away?
# 3. What network do you use when you browse www.google.com from your
# smartphone (not connected to the Wifi)

3
2
1

