#!/usr/bin/env bash
# displays 1 through 100
# Fizz if number is multiple of 3
# Buzz if number is multiple of 5
# FizzBuzz if number is multiple of 3 and 5

for num in $(seq 100)
do
	if (( num % 3 == 0 && num % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( num % 3 == 0 )); then
		echo "Fizz"
	elif (( num % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$num"
	fi
done
