#!/usr/bin/env bash
# printing Best School 10 times but for 8th iteration

counter=0

while [ $counter -lt 10 ]
do
	echo "Best School"
	if [ $counter -eq 8 ]
	then
		echo "Hi"
	fi
	((counter++))
done
