#!/usr/bin/env bash
#  loops from 1 to 10 and: displays bad luck, good luck in 4 and 8, otherwise  Best School

counter=1

while [ $counter -lt 11 ]
do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
